### ISSUE TITLE
Launchpads deal damage

### ISSUE THREAD

**Issue by ghost** [MCPEPIG/LaunchPads#1]
Can you fix it :) nice plugin

**Comment by DaPigGuy** [comment]
Ill try to fix this in the next update. Thanks

**Comment by ghost** [comment]
how it's going

**Comment by dries-c** [comment]
He dont have work

**Comment by DaPigGuy** [comment]
This will be worked on in a bit.

**Comment by DaPigGuy** [comment]
Fixed
